services:
  versa-atende-builder-base:
    image: versa-atende-builder:latest
  server:
    # Hot-reload + modo dev
    command: npm run dev:api:debug
    environment:
      - NODE_ENV=development
      - NEXT_ENABLED=false
    volumes:
      - .:/app:delegated
      - /app/node_modules
    ports:
      - "3000:3000"
      - "24678:24678"             # opcional: VSCode debugger

  broadcast-test:
    container_name: versa-atende-broadcast-test
    extends:
      service: versa-atende-builder-base
    command: npm run test:broadcast
    environment:
      - SERVER_URL=http://versa-atende-painel-server:3000
      - CHANNEL=recepcao_01
    depends_on:
      server:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - .:/app:cached
      - /app/node_modules
      - /app/dist-test

  jest:
    container_name: versa-atende-api-jest
    extends:
      service: versa-atende-builder-base
    command: npm test -- --watchAll=false  # Run único; mude para --watchAll para modo watch
    environment:
      - NODE_ENV=test
    depends_on:
      db:
        condition: service_healthy  # Opcional para unitários
    networks:
      - app-network
    volumes:
      - .:/app:cached
      - /app/node_modules
    tty: true
    stdin_open: true

  migrate:
    entrypoint: ["npx", "prisma", "migrate", "dev"]
    command: []
    tty: true
    stdin_open: true
    volumes:
      - .:/app:cached
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network